# Site settings
title: Neo Workspace
tagline: Built for large screens, multitasking and privacy.
description: >
  Neo Workspace allows you to view multiple web pages side by side in one window and multitask more easily, it has password manager, spellcheck, 
  flexible layout, dark theme and a lot more.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
author: NeoNav
lang: en_US
twitter:
  username: neonav_co
  card: summary
# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 2
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
