# Site settings
title: Neo Workspace
tagline: A new way to navigate websites
description: >
  Neo Workspace is a smart tiling window manager for your websites, with features such as password manager, spellcheck, multiple workspaces, 
  flexible layout, data auto saving and dark theme.
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
author: NeoNav
lang: en_US
twitter:
  username: neonav_co
  card: summary
# Build settings
safe: true # always trues on github-pages, disables _plugins/
markdown: kramdown
sass:
  indentWidth: 2
  style: compressed
  precision: 10
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
exclude:
  - Gemfile
  - Gemfile.lock
  - build-in-docker.sh
  - README.md
